import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, BookOpen, CalendarDays, Eye, FileCheck2, ImagePlus, MoreHorizontal, Plus, Save, ShoppingBag, UploadCloud } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { adminApi } from '../api/client';
import { toAdminBookInput } from '../api/books';
import { uploadPrivateFile } from '../api/uploads';
import type { Book, BookStatus, CursorPage } from '../types';
import { money, monthYear } from '../types';
import { Card, Empty, ErrorState, Loading, Modal, PageHeader, SearchBox, Status } from '../components/Ui';

export function BooksPage({ status, title = 'Books', latest = false }: { status?: BookStatus; title?: string; latest?: boolean }) {
  const [queryText, setQueryText] = useState(''); const [selectedStatus, setSelectedStatus] = useState<BookStatus | ''>(status || ''); const [confirm, setConfirm] = useState<Book | null>(null); const queryClient = useQueryClient();
  const books = useQuery({ queryKey: ['books', selectedStatus, queryText, latest], queryFn: () => adminApi.get<CursorPage<Book>>(`/admin/books?${new URLSearchParams({ ...(selectedStatus ? { status: selectedStatus } : {}), ...(queryText ? { query: queryText } : {}), ...(latest ? { latest: 'true' } : {}) })}`) });
  const archive = useMutation({ mutationFn: (id: string) => adminApi.post(`/admin/books/${id}/archive`), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['books'] }); setConfirm(null); } });
  return <><PageHeader title={title} subtitle={latest ? 'Books currently within the configured Latest duration.' : status === 'UPCOMING' ? 'Prepare, pre-book and publish future stories.' : 'Create and manage the complete MOSTLYVERS catalogue.'} action={<Link className="btn btn-primary" to="/books/new"><Plus size={16}/> ADD NEW BOOK</Link>} />
    <Card className="toolbar"><SearchBox value={queryText} onChange={setQueryText} placeholder="Search books…" /><select aria-label="Book status" value={selectedStatus} onChange={event => setSelectedStatus(event.target.value as BookStatus | '')}><option value="">All Status</option><option>DRAFT</option><option>UPCOMING</option><option>PUBLISHED</option><option>ARCHIVED</option></select></Card>
    {books.isPending ? <Loading label="Loading books…" /> : books.isError ? <ErrorState error={books.error} retry={() => books.refetch()} /> : books.data.items.length === 0 ? <Empty message="No books match this view." /> : <Card className="table-card"><div className="data-table book-table"><div className="table-head"><span>Book</span><span>Publication</span><span>Price</span><span>Status</span><span>Purchases</span><span>Catalog</span><span>Actions</span></div>{books.data.items.map(book => <div className="table-row" key={book.id}><div className="book-cell"><img src={book.coverUrl}/><div><strong>{book.title}</strong><small>{book.shortDescription}</small></div></div><span><CalendarDays size={14}/>{monthYear(book.publicationMonth, book.publicationYear)}</span><strong>{money(book.price)}</strong><Status value={book.status}/><span><ShoppingBag size={14}/>{book.purchaseCount}</span><Status value={book.catalogStatus}/><div className="table-actions"><Link className="icon-btn" title="Edit book" to={`/books/${book.id}`}><Eye size={17}/></Link><button className="icon-btn" title="Archive book" onClick={() => setConfirm(book)}><Archive size={17}/></button><button className="icon-btn"><MoreHorizontal size={17}/></button></div></div>)}</div></Card>}
    {confirm && <Modal title="Archive this book?" onClose={() => setConfirm(null)}><p><b>{confirm.title}</b> will leave the public catalogue. Existing ownership and historical transactions remain unchanged.</p><div className="dialog-actions"><button className="btn btn-outline" onClick={() => setConfirm(null)}>CANCEL</button><button className="btn btn-danger" onClick={() => archive.mutate(confirm.id)}>ARCHIVE</button></div></Modal>}
  </>;
}

const blank: Partial<Book> = { title: '', shortDescription: '', publicationMonth: new Date().getMonth() + 1, publicationYear: new Date().getFullYear(), price: { amountMinor: 0, currency: 'INR' }, status: 'DRAFT', prebook: { enabled: false, discountPercent: 15, count: 0 }, contentStatus: 'MISSING', catalogStatus: 'NOT_CONFIGURED' };

export function BookEditorPage() {
  const { bookId } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient();
  const detail = useQuery({ queryKey: ['book', bookId], queryFn: () => adminApi.get<Book>(`/admin/books/${bookId}`), enabled: Boolean(bookId), refetchInterval: query => query.state.data?.contentStatus === 'PROCESSING' ? 2_000 : false });
  const [form, setForm] = useState<Partial<Book>>(blank); const [dirty, setDirty] = useState(false); const [upload, setUpload] = useState<{ label: string; progress: number } | null>(null); const [uploadError, setUploadError] = useState(''); const [publishOpen, setPublishOpen] = useState(false);
  useEffect(() => { if (detail.data) setForm(detail.data); }, [detail.data]);
  useEffect(() => { const before = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', before); return () => window.removeEventListener('beforeunload', before); }, [dirty]);
  const update = <K extends keyof Book>(key: K, value: Book[K]) => { setForm(current => ({ ...current, [key]: value })); setDirty(true); };
  const save = useMutation({ mutationFn: () => bookId ? adminApi.patch<Book>(`/admin/books/${bookId}`, toAdminBookInput(form)) : adminApi.post<Book>('/admin/books', toAdminBookInput(form)), onSuccess: book => { setDirty(false); queryClient.invalidateQueries({ queryKey: ['books'] }); navigate(`/books/${book.id}`, { replace: true }); } });
  const publish = useMutation({ mutationFn: () => adminApi.post(`/admin/books/${bookId}/publish`), onSuccess: () => { setPublishOpen(false); queryClient.invalidateQueries({ queryKey: ['books'] }); queryClient.invalidateQueries({ queryKey: ['book', bookId] }); } });
  const chooseFile = async (file: File, kind: 'BOOK_COVER' | 'EPUB') => { setUploadError(''); setUpload({ label: file.name, progress: 0 }); try { const result = await uploadPrivateFile(file, kind, progress => setUpload({ label: file.name, progress })); if (kind === 'EPUB') { update('contentUploadRef', result.uploadRef); update('contentFileName', file.name); update('contentStatus', 'PROCESSING'); } else { update('coverUploadRef', result.uploadRef); update('coverUrl', URL.createObjectURL(file)); } } catch (error) { setUploadError(error instanceof Error ? error.message : 'The file could not be uploaded.'); } finally { setTimeout(() => setUpload(null), 600); } };
  if (bookId && detail.isPending) return <Loading label="Opening book editor…" />;
  if (detail.isError) return <ErrorState error={detail.error} />;
  const price = (form.price?.amountMinor || 0) / 100;
  return <><PageHeader title={bookId ? 'Edit Book' : 'Add New Book'} subtitle="Manage content, publication, pricing, pre-booking and YouTube access." action={<div className="quick-actions"><button className="btn btn-outline" onClick={() => navigate(-1)}>CANCEL</button><button className="btn btn-primary" disabled={save.isPending || !form.title} onClick={() => save.mutate()}><Save size={16}/>{save.isPending ? 'SAVING…' : 'SAVE CHANGES'}</button></div>} />
    <div className="editor-grid"><Card className="cover-editor"><h2>Book Cover</h2><div className="cover-preview">{form.coverUrl ? <img src={form.coverUrl}/> : <ImagePlus size={44}/>}</div><label className="btn btn-outline file-button"><ImagePlus size={16}/> CHANGE COVER<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => event.target.files?.[0] && chooseFile(event.target.files[0], 'BOOK_COVER')} /></label><div className="content-file"><FileCheck2/><div><strong>{form.contentFileName || 'No EPUB uploaded'}</strong><small>{form.contentStatus}</small></div></div><label className="btn btn-outline file-button"><UploadCloud size={16}/> {form.contentFileName ? 'REPLACE EPUB' : 'UPLOAD EPUB'}<input type="file" accept="application/epub+zip,.epub" onChange={event => event.target.files?.[0] && chooseFile(event.target.files[0], 'EPUB')} /></label>{upload && <div className="upload-progress"><span>{upload.label}</span><div><i style={{ width: `${upload.progress}%` }}/></div><b>{upload.progress}%</b></div>}{uploadError && <div className="toast-error">{uploadError}</div>}</Card>
      <Card className="book-form"><h2>Book Information</h2><div className="form-grid"><label className="field wide"><span>Book Title</span><input value={form.title || ''} onChange={event => update('title', event.target.value)} placeholder="Enter book title" /></label><label className="field wide"><span>Short Description</span><textarea rows={4} value={form.shortDescription || ''} onChange={event => update('shortDescription', event.target.value)} placeholder="Enter reader-facing description" /></label><label className="field"><span>Publication Month</span><select value={form.publicationMonth} onChange={event => update('publicationMonth', Number(event.target.value))}>{Array.from({ length: 12 }, (_, index) => <option value={index + 1} key={index}>{new Date(2026, index).toLocaleString('en', { month: 'long' })}</option>)}</select></label><label className="field"><span>Publication Year</span><input type="number" value={form.publicationYear} onChange={event => update('publicationYear', Number(event.target.value))}/></label><label className="field"><span>Price (₹)</span><input type="number" min="0" step="1" value={price} onChange={event => update('price', { amountMinor: Math.round(Number(event.target.value) * 100), currency: 'INR' })}/></label><label className="field"><span>Book Status</span><select value={form.status} disabled={form.status === 'PUBLISHED' || form.status === 'ARCHIVED'} onChange={event => update('status', event.target.value as BookStatus)}>{form.status === 'PUBLISHED' || form.status === 'ARCHIVED' ? <option>{form.status}</option> : <><option>DRAFT</option><option>UPCOMING</option></>}</select></label></div>
        <div className="settings-block"><Toggle label="Pre-book Available" checked={form.prebook?.enabled || false} onChange={value => update('prebook', { ...(form.prebook || { discountPercent: 15, count: 0 }), enabled: value })}/>{form.prebook?.enabled && <label className="field compact"><span>Pre-book Discount (%)</span><input type="number" min="0" max="90" value={form.prebook.discountPercent} onChange={event => update('prebook', { ...form.prebook!, discountPercent: Number(event.target.value) })}/></label>}</div>
        <div className="youtube-fields"><h2>YouTube Song</h2><Toggle label="YouTube Song Available" checked={Boolean(form.youtubeAsset)} onChange={value => update('youtubeAsset', value ? { songName: '', youtubeUrl: '', qrStatus: 'PENDING' } : undefined)}/>{form.youtubeAsset && <div className="form-grid"><label className="field"><span>Song / Video Name</span><input value={form.youtubeAsset.songName} onChange={event => update('youtubeAsset', { ...form.youtubeAsset!, songName: event.target.value })}/></label><label className="field"><span>YouTube URL</span><input type="url" value={form.youtubeAsset.youtubeUrl} onChange={event => update('youtubeAsset', { ...form.youtubeAsset!, youtubeUrl: event.target.value })}/></label></div>}</div>
		{bookId && <div className="publish-bar"><div><BookOpen/><span><strong>Ready to publish?</strong><small>Publishing adds the book to the reader app and converts active pre-books into ownership.</small></span></div><button className="btn btn-primary" disabled={form.contentStatus !== 'VALID'} onClick={() => setPublishOpen(true)}>PUBLISH BOOK</button></div>}
      </Card></div>
	{save.isError && <div className="toast-error">{save.error.message}</div>}{publishOpen && <Modal title="Publish this book?" onClose={() => setPublishOpen(false)}><p>This adds <b>{form.title}</b> to the Android catalogue, starts its Latest window, and converts active free-launch pre-books. This action is audited.</p><div className="dialog-actions"><button className="btn btn-outline" onClick={() => setPublishOpen(false)}>CANCEL</button><button className="btn btn-primary" onClick={() => publish.mutate()}>{publish.isPending ? 'PUBLISHING…' : 'PUBLISH'}</button></div></Modal>}
  </>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><button type="button" role="switch" aria-checked={checked} className={checked ? 'toggle on' : 'toggle'} onClick={() => onChange(!checked)}><i /></button></label>; }
