import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookOpen, CalendarDays, FileCheck2, ImagePlus, MoreHorizontal, Plus, RefreshCw, Save, Trash2, UploadCloud } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { adminApi } from '../api/client';
import { completeBookPublish, refreshBookViews } from '../api/adminConsistency';
import { bookListStatusFromSearch, bookNeedsProcessingPoll, saveThenPublishBook, toAdminBookInput, toCreateBookInput } from '../api/books';
import { uploadPrivateFile } from '../api/uploads';
import type { Book, BookStatus, CursorPage } from '../types';
import { bookPrice, monthYear } from '../types';
import { Card, Empty, ErrorState, Loading, Modal, PageHeader, SearchBox, Status } from '../components/Ui';

type ActionName = 'publish' | 'archive' | 'delete';
const contentLabel = (book: Book) => book.contentStatus === 'PROCESSING' ? 'Processing' : book.contentStatus === 'FAILED' ? 'Processing failed' : book.contentStatus === 'VALID' && (book.status === 'DRAFT' || book.status === 'UPCOMING') ? 'Ready to publish' : book.contentStatus === 'VALID' ? 'Content ready' : 'EPUB missing';

function BookCover({ book }: { book: Pick<Book, 'coverUrl' | 'title'> }) {
  return book.coverUrl ? <img src={book.coverUrl} alt="" /> : <span className="book-cover-placeholder" aria-label={`${book.title} has no cover`}><i>MV</i><b>{book.title}</b></span>;
}

export function BooksPage({ status, title = 'Books', latest = false }: { status?: BookStatus; title?: string; latest?: boolean }) {
  const [searchParams, setSearchParams] = useSearchParams();
  const selectedStatus = status || bookListStatusFromSearch(`?${searchParams.toString()}`);
  const [queryText, setQueryText] = useState('');
  const [action, setAction] = useState<{ book: Book; name: ActionName } | null>(null);
  const [message, setMessage] = useState('');
  const queryClient = useQueryClient();
  const books = useQuery({
    queryKey: ['books', selectedStatus, queryText, latest],
    queryFn: () => adminApi.get<CursorPage<Book>>(`/admin/books?${new URLSearchParams({ ...(selectedStatus ? { status: selectedStatus } : {}), ...(queryText ? { query: queryText } : {}), ...(latest ? { latest: 'true' } : {}) })}`),
    refetchInterval: query => bookNeedsProcessingPoll(query.state.data?.items || []) ? 5_000 : false,
  });
  const mutation = useMutation({
    mutationFn: ({ book, name }: { book: Book; name: ActionName }) => name === 'delete' ? adminApi.delete(`/admin/books/${book.id}`) : adminApi.post(`/admin/books/${book.id}/${name}`),
    onSuccess: async (_result, variables) => { setMessage(variables.name === 'delete' ? 'Book deleted. Storage cleanup is running safely in the background.' : `Book ${variables.name === 'publish' ? 'published' : 'archived'} successfully.`); setAction(null); await refreshBookViews(queryClient, variables.book.id); },
  });
  const selectStatus = (value: string) => { const next = new URLSearchParams(searchParams); if (value) next.set('status', value); else next.delete('status'); setSearchParams(next, { replace: true }); };
  return <><PageHeader title={title} subtitle={latest ? 'Books currently within the configured Latest duration.' : status === 'UPCOMING' ? 'Prepare, pre-book and publish future stories.' : 'Create and manage the complete MOSTLYVERS catalogue.'} action={<Link className="btn btn-primary" to="/books/new"><Plus size={16}/> ADD NEW BOOK</Link>} />
    <Card className="toolbar"><SearchBox value={queryText} onChange={setQueryText} placeholder="Search books…" /><select aria-label="Book status" value={selectedStatus} disabled={Boolean(status)} onChange={event => selectStatus(event.target.value)}><option value="">All Status</option><option>DRAFT</option><option>UPCOMING</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button className="btn btn-outline" disabled={books.isFetching} onClick={() => books.refetch()}><RefreshCw size={15} className={books.isFetching ? 'spin' : ''}/> REFRESH</button>{books.dataUpdatedAt > 0 && <small className="last-updated">Updated {new Date(books.dataUpdatedAt).toLocaleTimeString()}</small>}</Card>
    {message && <div className="success-banner" role="status">{message}</div>}
    {books.isPending ? <Loading label="Loading books…" /> : books.isError ? <ErrorState error={books.error} retry={() => books.refetch()} /> : books.data.items.length === 0 ? <Empty message="No books match this view." /> : <Card className="table-card"><div className="data-table book-table"><div className="table-head"><span>Book</span><span>Publication</span><span>Price</span><span>Status</span><span>Readers</span><span>Content</span><span>Actions</span></div>{books.data.items.map(book => <div className="table-row" key={book.id}><div className="book-cell"><BookCover book={book}/><div><strong>{book.title}</strong><small>{book.shortDescription || 'No description added'}</small></div></div><span><CalendarDays size={14}/>{monthYear(book.publicationMonth, book.publicationYear)}</span><strong>{bookPrice(book.price)}</strong><Status value={book.status}/><span>{book.purchaseCount}</span><span className="content-state"><Status value={contentLabel(book)}/>{book.contentStatus === 'PROCESSING' && <small>{book.contentProgress ?? 0}%</small>}{book.contentStatus === 'FAILED' && <small title={book.contentErrorCode}>{book.contentErrorCode || 'EPUB validation failed'}</small>}</span><details className="actions-menu"><summary className="icon-btn" aria-label={`Actions for ${book.title}`}><MoreHorizontal size={17}/></summary><div><Link to={`/books/${book.id}`}>Edit</Link><button disabled={!book.actions.canPublish} title={book.actions.publishBlockedReason} onClick={() => setAction({ book, name: 'publish' })}>Publish</button><button disabled={!book.actions.canArchive} title={!book.actions.canArchive ? 'Only Upcoming or Published books can be archived.' : undefined} onClick={() => setAction({ book, name: 'archive' })}>Archive</button>{book.contentStatus === 'FAILED' && <Link to={`/books/${book.id}?replace=epub`}>Replace EPUB</Link>}<button className="danger-link" disabled={!book.actions.canDelete} title={book.actions.deleteBlockedReason} onClick={() => setAction({ book, name: 'delete' })}><Trash2 size={13}/>Delete permanently</button>{!book.actions.canDelete && book.actions.deleteBlockedReason && <small>{book.actions.deleteBlockedReason}</small>}</div></details></div>)}</div></Card>}
    {action && <Modal title={`${action.name === 'delete' ? 'Delete permanently' : action.name === 'archive' ? 'Archive' : 'Publish'} this book?`} onClose={() => !mutation.isPending && setAction(null)}><p>{action.name === 'delete' ? <><b>{action.book.title}</b> and its unused content will be permanently removed. This cannot be undone.</> : action.name === 'archive' ? <><b>{action.book.title}</b> will leave the public catalogue. Existing reader access is preserved.</> : <><b>{action.book.title}</b> will become visible in the Android app as a free book.</>}</p>{mutation.isError && <div className="inline-error">{mutation.error.message}</div>}<div className="dialog-actions"><button className="btn btn-outline" disabled={mutation.isPending} onClick={() => setAction(null)}>CANCEL</button><button className={action.name === 'delete' ? 'btn btn-danger' : 'btn btn-primary'} disabled={mutation.isPending} onClick={() => mutation.mutate(action)}>{mutation.isPending ? 'WORKING…' : 'CONFIRM'}</button></div></Modal>}
  </>;
}

const now = new Date();
const blank: Partial<Book> = { title: '', shortDescription: '', publicationMonth: now.getMonth() + 1, publicationYear: now.getFullYear(), price: { amountMinor: 0, currency: 'INR' }, status: 'DRAFT', prebook: { enabled: false, discountPercent: 15, count: 0 }, contentStatus: 'MISSING', catalogStatus: 'NOT_CONFIGURED', actions: { canEdit: true, canPublish: false, canArchive: false, canDelete: true } };

export function BookEditorPage() {
  const { bookId } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const abortUpload = useRef<AbortController | null>(null);
  const detail = useQuery({ queryKey: ['book', bookId], queryFn: () => adminApi.get<Book>(`/admin/books/${bookId}`), enabled: Boolean(bookId), refetchInterval: query => query.state.data?.contentStatus === 'PROCESSING' ? 5_000 : false });
  const [form, setForm] = useState<Partial<Book>>(blank); const [dirty, setDirty] = useState(false);
  const [upload, setUpload] = useState<{ kind: 'BOOK_COVER' | 'EPUB'; file: File; progress: number; state: 'UPLOADING' | 'DONE' | 'FAILED' } | null>(null);
  const [uploadError, setUploadError] = useState(''); const [publishOpen, setPublishOpen] = useState(false);
  useEffect(() => { if (detail.data) setForm(detail.data); }, [detail.data]);
  useEffect(() => { const before = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', before); return () => window.removeEventListener('beforeunload', before); }, [dirty]);
  const update = <K extends keyof Book>(key: K, value: Book[K]) => { setForm(current => ({ ...current, [key]: value })); setDirty(true); };
  const save = useMutation({ mutationFn: () => bookId ? adminApi.patch<Book>(`/admin/books/${bookId}`, toAdminBookInput(form)) : adminApi.post<Book>('/admin/books', toCreateBookInput(form)), onSuccess: async book => { setDirty(false); await refreshBookViews(queryClient, book.id); navigate(bookId ? `/books/${book.id}` : '/books?status=DRAFT', { replace: true }); } });
  const publish = useMutation({ mutationFn: () => saveThenPublishBook(adminApi, bookId!, form, dirty), onSuccess: async savedBook => { setForm(savedBook); setDirty(false); setPublishOpen(false); await completeBookPublish(queryClient, bookId!, navigate); } });
  const chooseFile = async (file: File, kind: 'BOOK_COVER' | 'EPUB') => {
    setUploadError(''); const controller = new AbortController(); abortUpload.current = controller; setUpload({ kind, file, progress: 0, state: 'UPLOADING' });
    try { const result = await uploadPrivateFile(file, kind, progress => setUpload(current => current ? { ...current, progress } : current), controller.signal); if (kind === 'EPUB') { update('contentUploadRef', result.uploadRef); update('contentFileName', file.name); update('contentStatus', 'PROCESSING'); } else { update('coverUploadRef', result.uploadRef); update('coverUrl', URL.createObjectURL(file)); } setUpload(current => current ? { ...current, progress: 100, state: 'DONE' } : current); }
    catch (error) { setUploadError(error instanceof Error ? error.message : 'The file could not be uploaded.'); setUpload(current => current ? { ...current, state: 'FAILED' } : current); }
    finally { abortUpload.current = null; }
  };
  if (bookId && detail.isPending) return <Loading label="Opening book editor…" />;
  if (detail.isError) return <ErrorState error={detail.error} retry={() => detail.refetch()} />;
  const uploading = upload?.state === 'UPLOADING'; const titleValid = Boolean(form.title?.trim()); const epubReady = Boolean(form.contentUploadRef || (bookId && form.contentStatus !== 'MISSING'));
  return <><PageHeader title={bookId ? 'Edit Book' : 'Add New Book'} subtitle={bookId ? 'Update book details and replace content when needed.' : 'A title and EPUB are all you need. Everything else is optional.'} action={<div className="quick-actions"><button className="btn btn-outline" onClick={() => navigate(-1)}>CANCEL</button><button className="btn btn-primary" disabled={save.isPending || uploading || !titleValid || !epubReady} onClick={() => save.mutate()}><Save size={16}/>{save.isPending ? 'SAVING…' : bookId ? 'SAVE CHANGES' : 'SAVE DRAFT'}</button></div>} />
    <div className="simple-book-editor"><Card className="book-form primary-book-fields"><h2>Required</h2><label className="field"><span>Book Title</span><input autoFocus value={form.title || ''} onChange={event => update('title', event.target.value)} placeholder="Enter book title" /></label><div className="epub-drop"><FileCheck2/><div><strong>{form.contentFileName || 'Upload an EPUB book'}</strong><small>{form.contentStatus === 'VALID' ? 'Validated and ready' : form.contentStatus === 'FAILED' ? 'Processing failed — replace this file' : form.contentStatus === 'PROCESSING' ? 'Uploaded — processing continues after save' : 'EPUB is required'}</small></div><label className="btn btn-outline file-button"><UploadCloud size={16}/> {form.contentFileName ? 'REPLACE EPUB' : 'CHOOSE EPUB'}<input type="file" accept="application/epub+zip,.epub" onChange={event => event.target.files?.[0] && chooseFile(event.target.files[0], 'EPUB')} /></label></div>{upload?.kind === 'EPUB' && <div className="upload-progress"><span>{upload.file.name}</span><div><i style={{ width: `${upload.progress}%` }}/></div><b>{upload.state === 'FAILED' ? 'Failed' : upload.state === 'DONE' ? 'Upload complete' : `${upload.progress}%`}</b><div className="upload-controls">{upload.state === 'UPLOADING' && <button className="text-button" onClick={() => abortUpload.current?.abort()}>Cancel</button>}{upload.state === 'FAILED' && <button className="text-button" onClick={() => chooseFile(upload.file, 'EPUB')}>Retry</button>}</div></div>}{uploadError && <div className="inline-error">{uploadError}</div>}</Card>
      <details className="optional-details" open={Boolean(bookId)}><summary>Optional details</summary><Card className="optional-grid"><div><h2>Cover</h2><div className="cover-preview">{form.coverUrl ? <img src={form.coverUrl} alt="Book cover preview"/> : <span className="large-cover-placeholder"><i>MV</i><b>{form.title || 'Your book title'}</b></span>}</div><label className="btn btn-outline file-button"><ImagePlus size={16}/> {form.coverUrl ? 'CHANGE COVER' : 'ADD COVER'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => event.target.files?.[0] && chooseFile(event.target.files[0], 'BOOK_COVER')} /></label></div><div className="book-form"><label className="field"><span>Short Description</span><textarea rows={4} value={form.shortDescription || ''} onChange={event => update('shortDescription', event.target.value)} placeholder="Optional reader-facing description" /></label><div className="form-grid"><label className="field"><span>Publication Month</span><select value={form.publicationMonth} onChange={event => update('publicationMonth', Number(event.target.value))}>{Array.from({ length: 12 }, (_, index) => <option value={index + 1} key={index}>{new Date(2026, index).toLocaleString('en', { month: 'long' })}</option>)}</select></label><label className="field"><span>Publication Year</span><input type="number" value={form.publicationYear} onChange={event => update('publicationYear', Number(event.target.value))}/></label></div><div className="free-price-note"><strong>Price: Free</strong><small>Pricing is locked to ₹0 during FREE_LAUNCH.</small></div><div className="settings-block"><h2>Pre-book</h2>{bookId ? <><Toggle label="Pre-book Available" checked={form.prebook?.enabled || false} onChange={value => update('prebook', { ...(form.prebook || { discountPercent: 15, count: 0 }), enabled: value })}/>{form.prebook?.enabled && <label className="field compact"><span>Discount (%)</span><input type="number" min="0" max="90" value={form.prebook.discountPercent} onChange={event => update('prebook', { ...form.prebook!, discountPercent: Number(event.target.value) })}/></label>}</> : <small>Save the draft first, then edit it to enable pre-booking.</small>}</div><div className="youtube-fields"><h2>YouTube Song</h2><Toggle label="Add YouTube details" checked={Boolean(form.youtubeAsset)} onChange={value => update('youtubeAsset', value ? { songName: '', youtubeUrl: '', qrStatus: 'PENDING' } : undefined)}/>{form.youtubeAsset && <div className="form-grid"><label className="field"><span>Song / Video Name</span><input value={form.youtubeAsset.songName} onChange={event => update('youtubeAsset', { ...form.youtubeAsset!, songName: event.target.value })}/></label><label className="field"><span>YouTube URL</span><input type="url" value={form.youtubeAsset.youtubeUrl} onChange={event => update('youtubeAsset', { ...form.youtubeAsset!, youtubeUrl: event.target.value })}/></label></div>}</div></div></Card></details>
      {bookId && (form.status === 'DRAFT' || form.status === 'UPCOMING') && <Card className="publish-bar"><div><BookOpen/><span><strong>{form.actions?.canPublish && form.contentStatus === 'VALID' ? 'Ready to publish' : 'Publish unavailable'}</strong><small>{form.contentStatus !== 'VALID' ? 'Wait for EPUB processing to finish successfully.' : form.actions?.publishBlockedReason || 'Publishing makes this free book visible in the Android app.'}</small></span></div><button className="btn btn-primary" disabled={form.contentStatus !== 'VALID' || !form.actions?.canPublish || save.isPending || publish.isPending} title={form.actions?.publishBlockedReason} onClick={() => setPublishOpen(true)}>PUBLISH BOOK</button></Card>}
    </div>
    {save.isError && <div className="toast-error">{save.error.message}</div>}{publish.isError && <div className="toast-error">{publish.error.message}</div>}{publishOpen && <Modal title="Publish this book?" onClose={() => setPublishOpen(false)}><p>This adds <b>{form.title}</b> to the Android catalogue as a free book. A cover is optional.</p><div className="dialog-actions"><button className="btn btn-outline" onClick={() => setPublishOpen(false)}>CANCEL</button><button className="btn btn-primary" disabled={publish.isPending} onClick={() => publish.mutate()}>{publish.isPending ? 'PUBLISHING…' : 'PUBLISH'}</button></div></Modal>}
  </>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><button type="button" role="switch" aria-checked={checked} className={checked ? 'toggle on' : 'toggle'} onClick={() => onChange(!checked)}><i /></button></label>; }
