import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { CircleDollarSign, Download, ReceiptText, RotateCcw, ShoppingBag } from 'lucide-react';
import { adminApi } from '../api/client';
import type { CursorPage, Transaction } from '../types';
import { money } from '../types';
import { Card, ErrorState, Loading, PageHeader, Status } from '../components/Ui';

export function SalesPage() {
  const [type, setType] = useState(''); const [status, setStatus] = useState(''); const query = useQuery({ queryKey: ['transactions'], queryFn: () => adminApi.get<CursorPage<Transaction>>('/admin/transactions') });
  const filtered = useMemo(() => query.data?.items.filter(item => (!type || item.type === type) && (!status || item.status === status)) || [], [query.data, type, status]);
  if (query.isPending) return <Loading label="Loading sales…" />; if (query.isError) return <ErrorState error={query.error} />;
  const total = query.data.items.filter(item => item.status === 'COMPLETED').reduce((sum, item) => sum + item.amount.amountMinor, 0); const types = ['BOOK_PURCHASE', 'PREBOOK', 'DEVICE_TRANSFER'].map(value => ({ name: value.replaceAll('_', ' '), value: query.data.items.filter(item => item.type === value).reduce((sum, item) => sum + item.amount.amountMinor, 0) / 100 }));
  return <><PageHeader title="Sales & Revenue" subtitle="Verified transactions, pre-book sales, transfer fees and refund status." action={<button className="btn btn-outline" onClick={() => downloadCsv(filtered)}><Download size={16}/> EXPORT CSV</button>} /><div className="sales-metrics"><Card><ShoppingBag/><div><strong>{query.data.total}</strong><span>Total Transactions</span></div></Card><Card><CircleDollarSign/><div><strong>{money({ amountMinor: total, currency: 'INR' })}</strong><span>Completed Revenue</span></div></Card><Card><RotateCcw/><div><strong>{query.data.items.filter(item => item.status === 'REFUNDED').length}</strong><span>Refunded</span></div></Card></div>
    <div className="dashboard-grid"><Card><div className="card-title-row"><h2>Revenue by Type</h2></div><ResponsiveContainer height={260} width="100%"><PieChart><Pie data={types} dataKey="value" nameKey="name" innerRadius={60} outerRadius={92} paddingAngle={3}>{['#5368a8', '#d97969', '#c6a354'].map(color => <Cell fill={color} key={color}/>)}</Pie><Tooltip formatter={value => `₹${Number(value).toLocaleString('en-IN')}`}/></PieChart></ResponsiveContainer><div className="chart-legend">{types.map((item, index) => <span key={item.name}><i style={{ background: ['#5368a8', '#d97969', '#c6a354'][index] }}/>{item.name}: ₹{item.value.toLocaleString('en-IN')}</span>)}</div></Card><Card className="sales-summary"><ReceiptText/><h2>{money({ amountMinor: total, currency: 'INR' })}</h2><p>Historical amounts remain immutable when future prices and fees change.</p></Card></div>
    <Card className="toolbar"><select value={type} onChange={event => setType(event.target.value)}><option value="">All Transaction Types</option><option value="BOOK_PURCHASE">Book Purchase</option><option value="PREBOOK">Pre-book</option><option value="DEVICE_TRANSFER">Device Change</option></select><select value={status} onChange={event => setStatus(event.target.value)}><option value="">All Statuses</option><option>COMPLETED</option><option>PENDING</option><option>FAILED</option><option>REFUNDED</option></select></Card><Card className="table-card"><div className="data-table sales-table"><div className="table-head"><span>Reference</span><span>Reader</span><span>Type</span><span>Book</span><span>Amount</span><span>Date</span><span>Status</span></div>{filtered.map(item => <div className="table-row" key={item.id}><code>{item.id}</code><strong>{item.readerName}</strong><span>{item.type.replaceAll('_', ' ')}</span><span>{item.bookTitle || '—'}</span><b>{money(item.amount)}</b><span>{new Date(item.createdAt).toLocaleString('en-IN')}</span><Status value={item.status}/></div>)}</div></Card>
  </>;
}
function downloadCsv(items: Transaction[]) { const csv = ['Reference,Reader,Type,Book,Amount Minor,Currency,Status,Created At', ...items.map(item => [item.id, item.readerName, item.type, item.bookTitle || '', item.amount.amountMinor, item.amount.currency, item.status, item.createdAt].map(value => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'mostlyvers-transactions.csv'; link.click(); URL.revokeObjectURL(link.href); }
