import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BadgeCheck, Building2, CircleDollarSign, ExternalLink, ImagePlus, LockKeyhole, Mail, Save, ShieldCheck } from 'lucide-react';
import { useAuth } from '../auth/AuthContext';
import { adminApi } from '../api/client';
import { uploadPrivateFile } from '../api/uploads';
import type { AppSettings, AuthorContent, ContactContent, Owner } from '../types';
import { Card, ErrorState, Loading, PageHeader, Status } from '../components/Ui';

export function ContentPage({ kind }: { kind: 'author' | 'contact' }) {
  const client = useQueryClient(); const path = kind === 'author' ? '/admin/content/author' : '/admin/content/contact';
  const query = useQuery({ queryKey: ['content', kind], queryFn: () => adminApi.get<AuthorContent | ContactContent>(path) }); const [form, setForm] = useState<any>(null); const [loadedKind, setLoadedKind] = useState<typeof kind>();
  useEffect(() => { if (query.data) { setForm(query.data); setLoadedKind(kind); } }, [query.data, kind]); const save = useMutation({ mutationFn: () => adminApi.patch(path, form), onSuccess: () => client.invalidateQueries({ queryKey: ['content', kind] }) });
  if (query.isError) return <ErrorState error={query.error} />; if (query.isPending || !form || loadedKind !== kind) return <Loading />;
  if (kind === 'author') { const author = form as AuthorContent; const changePhoto = async (file: File) => { const uploaded = await uploadPrivateFile(file, 'AUTHOR_PHOTO'); setForm({ ...author, photoUrl: URL.createObjectURL(file), photoUploadRef: uploaded.uploadRef }); }; return <><PageHeader title="About Author" subtitle="Changes appear automatically in the reader app and Home preview." action={<button className="btn btn-primary" disabled={save.isPending} onClick={() => save.mutate()}><Save size={16}/> {save.isPending ? 'SAVING…' : 'SAVE CHANGES'}</button>} /><div className="author-editor"><Card className="author-photo"><img src={author.photoUrl}/><label className="btn btn-outline file-button"><ImagePlus size={16}/> CHANGE PHOTO<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => event.target.files?.[0] && void changePhoto(event.target.files[0])}/></label></Card><Card className="form-card"><label className="field"><span>Author Name</span><input value={author.name} onChange={event => setForm({ ...author, name: event.target.value })}/></label><label className="field"><span>Short Biography</span><input value={author.shortBio} onChange={event => setForm({ ...author, shortBio: event.target.value })}/></label><label className="field"><span>Full Biography</span><textarea rows={8} value={author.fullBio} onChange={event => setForm({ ...author, fullBio: event.target.value })}/></label></Card></div></>; }
  const contact = form as ContactContent; return <><PageHeader title="Contact" subtitle="Reader-facing official channels update dynamically." action={<button className="btn btn-primary" onClick={() => save.mutate()}><Save size={16}/> SAVE CHANGES</button>} /><Card className="form-card"><div className="form-grid"><Field label="Instagram Username" value={contact.instagramUsername} change={value => setForm({ ...contact, instagramUsername: value })}/><Field label="Instagram Profile Link" value={contact.instagramUrl} change={value => setForm({ ...contact, instagramUrl: value })}/><Field label="YouTube Channel Name" value={contact.youtubeName} change={value => setForm({ ...contact, youtubeName: value })}/><Field label="YouTube Channel Link" value={contact.youtubeUrl} change={value => setForm({ ...contact, youtubeUrl: value })}/><Field label="Official MOSTLYVERS Email" value={contact.officialEmail} change={value => setForm({ ...contact, officialEmail: value })}/><Field label="Support Email (optional)" value={contact.supportEmail || ''} change={value => setForm({ ...contact, supportEmail: value })}/></div></Card></>;
}

export function SettingsPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['app-settings'], queryFn: () => adminApi.get<AppSettings>('/admin/settings/app') }); const [form, setForm] = useState<AppSettings | null>(null);
  useEffect(() => { if (query.data) setForm(query.data); }, [query.data]); const save = useMutation({ mutationFn: () => adminApi.patch<AppSettings>('/admin/settings/app', form!), onSuccess: data => { setForm(data); client.setQueryData(['app-settings'], data); } });
  if (query.isError) return <ErrorState error={query.error} />; if (query.isPending || !form) return <Loading />;
  return <><PageHeader title="App Settings" subtitle="Business rules and reader content without source-code changes." action={<button className="btn btn-primary" onClick={() => save.mutate()}><Save size={16}/> SAVE SETTINGS</button>} /><div className="settings-grid"><Card className="form-card"><h2>Reader Messages</h2><label className="field"><span>Welcome Message</span><input value={form.welcomeMessage} onChange={event => setForm({ ...form, welcomeMessage: event.target.value })}/></label><label className="field"><span>Thank-you Message</span><textarea rows={4} value={form.thankYouMessage} onChange={event => setForm({ ...form, thankYouMessage: event.target.value })}/></label><label className="field"><span>General App Information</span><textarea rows={7} value={form.aboutApp} onChange={event => setForm({ ...form, aboutApp: event.target.value })}/></label></Card><Card className="form-card"><h2>Business Rules</h2><label className="field"><span>Device Change Fee (₹)</span><input type="number" value={form.deviceChangeFee.amountMinor / 100} onChange={event => setForm({ ...form, deviceChangeFee: { amountMinor: Number(event.target.value) * 100, currency: 'INR' } })}/></label><label className="field"><span>Maximum Device Changes</span><input type="number" min="0" value={form.maximumDeviceChanges} onChange={event => setForm({ ...form, maximumDeviceChanges: Number(event.target.value) })}/></label><label className="field"><span>Default Pre-book Discount (%)</span><input type="number" min="0" max="90" value={form.defaultPrebookDiscount} onChange={event => setForm({ ...form, defaultPrebookDiscount: Number(event.target.value) })}/></label><label className="field"><span>Latest Duration (months)</span><input type="number" min="1" value={form.latestDurationMonths} onChange={event => setForm({ ...form, latestDurationMonths: Number(event.target.value) })}/></label><div className="policy-note"><ShieldCheck/><span>Changes apply to future activity. Historical transaction amounts and device-change audit records remain unchanged.</span></div></Card></div></>;
}

export function OwnerProfilePage() {
  const { session, updateOwner } = useAuth(); const [owner, setOwner] = useState<Owner>(session!.owner); const [profileUploadRef, setProfileUploadRef] = useState<string>(); const [saved, setSaved] = useState(false);
  const save = useMutation({ mutationFn: () => adminApi.patch<Owner>('/admin/me', { ...owner, profilePictureUploadRef: profileUploadRef }), onSuccess: value => { setOwner(value); updateOwner(value); setSaved(true); setTimeout(() => setSaved(false), 1800); } });
  const changePhoto = async (file: File) => { const uploaded = await uploadPrivateFile(file, 'OWNER_PHOTO'); setProfileUploadRef(uploaded.uploadRef); setOwner(current => ({ ...current, profilePictureUrl: URL.createObjectURL(file) })); };
  return <><PageHeader title="Owner Profile" subtitle="This identity is separate from all reader profiles." action={<button className="btn btn-primary" disabled={save.isPending} onClick={() => save.mutate()}><Save size={16}/> {save.isPending ? 'SAVING…' : 'SAVE PROFILE'}</button>} /><div className="author-editor"><Card className="author-photo"><img src={owner.profilePictureUrl}/><label className="btn btn-outline file-button"><ImagePlus size={16}/> CHANGE PHOTO<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => event.target.files?.[0] && void changePhoto(event.target.files[0])}/></label></Card><Card className="form-card"><Field label="Owner Name" value={owner.name} change={value => setOwner({ ...owner, name: value })}/><Field label="Email" value={owner.email} change={value => setOwner({ ...owner, email: value })}/><Field label="Phone" value={owner.phone} change={value => setOwner({ ...owner, phone: value })}/><div className="settings-actions"><button className="btn btn-outline"><Mail size={16}/> CHANGE EMAIL WITH VERIFICATION</button><button className="btn btn-outline"><LockKeyhole size={16}/> CHANGE PASSWORD</button></div>{saved && <div className="success-box">Profile changes saved.</div>}{save.isError && <div className="toast-error">{save.error.message}</div>}</Card></div></>;
}

export function PaymentSettingsPage() {
  const status = useQuery({ queryKey: ['payment-status'], queryFn: () => adminApi.get<any>('/admin/payment-status') }); const settlement = useQuery({ queryKey: ['settlement'], queryFn: () => adminApi.get<any>('/admin/settlement') });
  const portal = useMutation({ mutationFn: () => adminApi.post<{ url: string }>('/admin/settlement/portal-session'), onSuccess: data => window.open(data.url, '_blank', 'noopener,noreferrer') });
  if (status.isPending || settlement.isPending) return <Loading />; if (status.isError || settlement.isError) return <ErrorState error={status.error || settlement.error} />;
  return <><PageHeader title="Payment Settings" subtitle="Provider connectivity, product synchronization and secure settlement status." /><div className="payment-grid"><Card className="integration-card"><div className="integration-icon play">▶</div><div><h2>Google Play Billing</h2><Status value={status.data.googlePlay}/><p>Book ownership and device-transfer payments are verified by the server before access is granted.</p><small>Last catalog sync: {status.data.lastCatalogSyncAt ? new Date(status.data.lastCatalogSyncAt).toLocaleString('en-IN') : 'Not configured'}</small></div></Card><Card className="integration-card"><div className="integration-icon"><CircleDollarSign/></div><div><h2>Alternative Billing</h2><Status value={status.data.alternativeBilling}/><p>Available only after eligible-region enrollment and external transaction reporting.</p></div></Card></div><Card className="settlement-card"><div className="settlement-title"><Building2/><div><h2>Bank & Settlement</h2><p>Managed securely by the payment provider.</p></div><BadgeCheck className="verified"/></div><dl><div><dt>Provider</dt><dd>{settlement.data.provider}</dd></div><div><dt>Account</dt><dd>{settlement.data.accountHint}</dd></div><div><dt>Status</dt><dd><Status value={settlement.data.status}/></dd></div><div><dt>Next settlement</dt><dd>{settlement.data.nextSettlementAt ? new Date(settlement.data.nextSettlementAt).toLocaleDateString('en-IN') : 'Not configured'}</dd></div></dl><button className="btn btn-primary" onClick={() => portal.mutate()}><ExternalLink size={16}/> MANAGE WITH PROVIDER</button><div className="policy-note"><LockKeyhole/><span>MOSTLYVERS never displays or stores bank passwords, UPI PINs, card PINs or gateway secrets in this dashboard.</span></div></Card></>;
}

function Field({ label, value, change }: { label: string; value: string; change: (value: string) => void }) { return <label className="field"><span>{label}</span><input value={value} onChange={event => change(event.target.value)}/></label>; }
